matrix:
  include:
    - language: dart
      
    - language: go
      go:
        - 1.x
        - "1.10"
        - 1.11.x
        - master
  
    - language: scala
      scala:
          - 2.9.3
          - 2.11.11